name: Terraform AWS apply

on:
  workflow_dispatch:

jobs:
   apply:
       name: apply
       runs-on: ubuntu-latest
       needs: terraform
       environment: dev
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v2
   
         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v1
           with:
             terraform_version: "0.15.0"
   
         - name: Download Plan Artifact
           uses: actions/download-artifact@v2
           with:
             name: tfplan
   
         - name: Terraform Init
           run: terraform init
       
         - name: Terraform Apply
           run: terraform apply -auto-approve tfplan
